### ISSUE TITLE
App session not being tracked on Android

### ISSUE THREAD

**Issue by cross19xx** [mixpanel/mixpanel-react-native#159]
## Dependencies
```json
{
  "dependencies": {
    "mixpanel-react-native": "2.0.1"
    "react": "18.0.0",
    "react-native": "0.69.1"
  }
}
```

```properties
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
```

## Initialization script
```javascript
import { Mixpanel } from 'mixpanel-react-native';

const trackAutomaticEvents = true;
const mixpanel = new Mixpanel("Token here", trackAutomaticEvents);

mixpanel.init();

// I simulated a delay to allow it time to run
setTimeout(() => {
  mixpanel.track('Test event');
}, 10000);
```

After the timeout was completed, I got this screen below:
<image src="https://user-images.githubusercontent.com/59402430/190012933-e398dfb2-f742-4f78-b143-cb812a494530.png" height="512px" />

In my logcat, I got the following:
```log
09-13 21:24:08.757 28109  4959 E unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: MixpanelReactNative.track got 5 arguments, expected 6
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:938)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at android.os.Looper.loopOnce(Looper.java:226)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:313)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
09-13 21:24:08.757 28109  4959 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:1012)
```

Does anyone have any idea how to resolve this? this started when I switched to version `2.0.0+`

**Comment by yenchulin** [comment]
same here😢

**Comment by cross19xx** [comment]
I created a repro of the app.
https://github.com/cross19xx/mixpanel-test

**Comment by zihejia** [comment]
hi @cross19xx , thanks for providing it. I'm taking a look.

**Comment by zihejia** [comment]
Hi @cross19xx, I apologize for the delayed response. If you use the latest version and clear the React Native (RN) cache, the issue should be resolved. This problem sometimes occurs when upgrading to a major release. I'm closing this one now but feel free to reopen if the problem still exists.
